### ISSUE TITLE
Wrong German Label

### ISSUE THREAD

**Issue by bequrios** [swiss/jolux#6]
For the vocabulary entry https://fedlex.data.admin.ch/vocabulary/consultation-stage/150, the German label (`skos:prefLabel`) is probably wrong, at the moment, it is: "Planen sie den rückzug ein" and should be something like "Planung wird zurückgezogen".

**Comment by Astro248** [comment]
Der Link, den du mir im Text geschickt hast, scheint nicht zu funktionieren. Ist das normal?

**Comment by bequrios** [comment]
> Der Link, den du mir im Text geschickt hast, scheint nicht zu funktionieren. Ist das normal?

Eigentlich müsste er automatisch weitergeleitet werden. Du solltest dann bei https://fedlex.data.admin.ch/de-CH/metadata?value=https:%2F%2Ffedlex.data.admin.ch%2Fvocabulary%2Fconsultation-stage%2F150 landen.

**Comment by Astro248** [comment]
Danke, dieser Link funktioniert jetzt.

**Comment by Astro248** [comment]
Du hattest Recht, es gab einen Fehler bei den Vokabeleinträgen. Ich habe bei den Berufsteams nachgeschaut. 
Der deutsche Begriff: „Planung ist zurückgezogen“.
Der Begriff auf Französisch: „Planification à retirer“.
Der Begriff auf Italienisch: „Ritirare la pianificazione“.

Die Berufsteams haben mir übermittelt, dass sie die Korrektur innerhalb von Casemates FO durchgeführt haben.

**Comment by bequrios** [comment]
ok, der deutsche Begriff ist nun: "Planung ist zurückzuziehen"
